server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arkhotech/cloud-config.git
          basedir: target/config
security:
  user:
    password: s3cret